### PR TITLE
test: add terratest and testing for metabase_vm

### PR DESCRIPTION
**Pull request by joshgamache**
Addresses #221. Depends on #219. Adds a testing framework for Terraform.

## Changes

- added Terratest and required frameworks/packages
- added a test for the `metabase_vm` module

## To test

In your console
1. Run `asdf install` to get `go`
2. Run `go mod tidy`
3. Run `export GOOGLE_PROJECT=emissions-elt-demo`
4. Run `go test terraform/modules/metabase_vm/metabase_vm_test.go -v -timeout 10m`
  - Test can take a few minutes, but should end with a Pass

### CODE REVIEW

**Comment by YaokunLin** [comment]
confirmed that test can be run on my local and it was a PASS
image

**Review by YaokunLin — APPROVED** [review]
This test essentially applies the metabase Terraform configurations, checks whether there were any errors, and then destroys the resources created by the Terraform configuration. I am approving this with a caveat that it doesn't subsequently check whether the resources were created correctly or behave as expected and the state of the resources

**Comment by joshgamache** [comment]
> Trivy found more than 10 potential problems in the proposed changes. Check the [Files changed](/button-inc/emissions-elt-demo/pull/222/files) tab for more details.

Potential problems detected by Trivy are part of upstream package dependencies for Terratest. It is _only_ used in testing Terraform deployment scripts. Alerts have been dismissed.

**Comment by joshgamache** [comment]
> This test essentially applies the metabase Terraform configurations, checks whether there were any errors, and then destroys the resources created by the Terraform configuration. I am approving this with a caveat that it doesn't subsequently check whether the resources were created correctly or behave as expected and the state of the resources

Good point. That's a good thing to flag, might be something to refactor for as Terratest is expanded to cover the rest of what Terraform is doing for Climate Trax.

**Pull request merged**
