### PR TITLE
Add users and roles to db

### PR DESCRIPTION
**Pull request by BallardRobinett**
added eed_internal role to test user

### CODE REVIEW

**Review by shon-button — COMMENTED** [review]
Could you explain the reason\result of the using the SQL command below:
SELECT eed_private.insert_user('eed_test_user', 'secret', 'eed_test_user@button.is');

**Comment by BallardRobinett** [comment]
> Could you explain the reason\result of the using the SQL command below:
SELECT eed_private.insert_user('eed_test_user', 'secret', '[eed_test_user@button.is](mailto:eed_test_user@button.is)');

this was to test the insert_user function I created, which inserts an entry into the table eed.users with the given username, password, and email

**Comment by shon-button** [comment]
> > Could you explain the reason\result of the using the SQL command below:
> > SELECT eed_private.insert_user('eed_test_user', 'secret', '[eed_test_user@button.is](mailto:eed_test_user@button.is)');
> 
> this was to test the insert_user function I created, which inserts an entry into the table eed.users with the given username, password, and email

Perhaps we can review the structure and use of the eed.users table. 
As background: Current App's authorization architecture is that the app will query the DB user table WHERE email is that as obtained by the OAuth provider.  So, for that functionality to work we need an email, and a role.  No need for the password as this is stored by auth provider.

**Comment by BallardRobinett** [comment]
> > > Could you explain the reason\result of the using the SQL command below:
> > > SELECT eed_private.insert_user('eed_test_user', 'secret', '[eed_test_user@button.is](mailto:eed_test_user@button.is)');
> > 
> > 
> > this was to test the insert_user function I created, which inserts an entry into the table eed.users with the given username, password, and email
> 
> Perhaps we can review the structure and use of the eed.users table. As background: Current App's authorization architecture is that the app will query the DB user table WHERE email is that as obtained by the OAuth provider. So, for that functionality to work we need an email, and a role. No need for the password as this is stored by auth provider.

yeah that makes sense

**Pull request closed without merging**
